// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKB0iZTs3EL9ZkCZYQ16Os1UqNoqB1Dq8',
    appId: '1:465388736606:web:c553ffff2885af0883e4cf',
    messagingSenderId: '465388736606',
    projectId: 'asmodeoweb-4931e',
    authDomain: 'asmodeoweb-4931e.firebaseapp.com',
    storageBucket: 'asmodeoweb-4931e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8cvwuCJ-wi4lkNkuHFrQFNNU-xypcqI',
    appId: '1:465388736606:android:d2db1af874025e2d83e4cf',
    messagingSenderId: '465388736606',
    projectId: 'asmodeoweb-4931e',
    storageBucket: 'asmodeoweb-4931e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsBGkwnlyS5-xGK7w6fLibYCvxR7QQLVM',
    appId: '1:465388736606:ios:7e04a55b64c7efbf83e4cf',
    messagingSenderId: '465388736606',
    projectId: 'asmodeoweb-4931e',
    storageBucket: 'asmodeoweb-4931e.firebasestorage.app',
    iosBundleId: 'com.example.asmodeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsBGkwnlyS5-xGK7w6fLibYCvxR7QQLVM',
    appId: '1:465388736606:ios:7e04a55b64c7efbf83e4cf',
    messagingSenderId: '465388736606',
    projectId: 'asmodeoweb-4931e',
    storageBucket: 'asmodeoweb-4931e.firebasestorage.app',
    iosBundleId: 'com.example.asmodeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKB0iZTs3EL9ZkCZYQ16Os1UqNoqB1Dq8',
    appId: '1:465388736606:web:a546016b3de0f10483e4cf',
    messagingSenderId: '465388736606',
    projectId: 'asmodeoweb-4931e',
    authDomain: 'asmodeoweb-4931e.firebaseapp.com',
    storageBucket: 'asmodeoweb-4931e.firebasestorage.app',
  );
}
